function mat = pca_example()
% define colors uwu
bg = [40/255, 40/255, 50/255];
scatter_face = [0.6, 0.6, 1];
scatter_edge = [0.8, 0.8, 0.8];
nred = [1, 0.5, 0.5];
ngrn = [0.5, 1, 0.5];
nblu = [0.5, 0.5, 1];
axis_etc = [0.7, 0.7, 0.7];
% -----------------
sig = [25,-1,7;-1,4,-4;7,-4,10];
dat = (generate_data(2000, [0,5,2], sig))';
PA = est_pa(sig);
PA1 = 3.*PA;

s = 10;
set(gcf, 'color', bg);
plot3([0 PA1(1,1)], [0 PA1(2,1)], [0 PA1(3,1)],...
    'LineWidth', 3,...
    'Color', nred); hold on;
plot3([0 PA1(1,2)], [0 PA1(2,2)], [0 PA1(3,2)],...
    'LineWidth', 3,...
    'Color', ngrn);
plot3([0 PA1(1,3)], [0 PA1(2,3)], [0 PA1(3,3)],...
    'LineWidth', 3,...
    'Color', nblu);
scatter3(dat(1,:), dat(2,:), dat(3,:),...
    s, scatter_face,...
    'MarkerEdgeColor', scatter_edge,...
    'MarkerFaceColor','flat');
axis equal;
set(gcf,'InvertHardCopy','Off');
grid(gca, 'on');
xlabel('x_1'); ylabel('x_2'); zlabel('x_3');
hold off;
set(gca, 'color', bg,...
    'XColor', axis_etc,...
    'YColor', axis_etc,...
    'ZColor', axis_etc);
view(gca,[-37.5 30]);

pause(30);

disp(PA);
rotated_data = PA' * dat;

s = 10;
subplot(3,1,1)
set(gcf, 'color', bg);
set(gcf,'InvertHardCopy','Off');
scatter(rotated_data(1,:), rotated_data(2,:),...
    s, scatter_face,...
    'MarkerEdgeColor', scatter_edge,...
    'MarkerFaceColor','flat');
set(gca, 'color', bg,...
    'XColor', nred,...
    'YColor', ngrn);
xlabel('y_1'); ylabel('y_2');
xlim([-25 25])
axis equal;
grid('on');

subplot(3,1,2)
scatter(rotated_data(2,:), rotated_data(3,:),...
        s, scatter_face,...
        'MarkerEdgeColor', scatter_edge,...
        'MarkerFaceColor','flat');
set(gca, 'color', bg,...
    'XColor', ngrn,...
    'YColor', nblu);
xlabel('y_2'); ylabel('y_3');
xlim([-25 25])
axis equal;
grid('on');

subplot(3,1,3)
scatter(rotated_data(1,:), rotated_data(3,:),...
        s, scatter_face,...
        'MarkerEdgeColor', scatter_edge,...
        'MarkerFaceColor','flat');
set(gca, 'color', bg,...
    'XColor', nred,...
    'YColor', nblu);
xlabel('y_1'); ylabel('y_3');
xlim([-25 25])
axis equal;
grid('on');